name: Get latest release branch
description: A simple action that returns the latest release branch given a pattern.
inputs:
  token:
    description: GitHub token with access to all necessary repositories
    required: true
  ownerRepo:
    description: Owner/repo which contains the branch (eg `grafana/grafana`)
    required: true
  pattern:
    description: The pattern to use to search for a release branch (eg `v11.3.x`)
    required: true
outputs:
  branch:
    description: The latest release branch that matches the pattern
    value: ${{ steps.get-latest-release-branch.outputs.branch }}
runs:
  using: composite
  steps:
    - id: build
      uses: ./build-go-binary
      with:
        binary_name: latest-release-branch

    - id: get-latest-release-branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_OWNERREPO: ${{ inputs.ownerRepo }}
        INPUT_PATTERN: ${{ inputs.pattern }}
        BINARY: ${{ steps.build.outputs.path }}
      run: |
        set -euo pipefail
        branch=$("${BINARY}")
        echo "branch=${branch}" >> "$GITHUB_OUTPUT"
