name: Create Security Branch
description: Creates a new security branch in a private repository for handling security fixes
inputs:
  release_branch:
    description: The release branch to create a security branch from (e.g., release-12.0.1)
    required: true
  security_branch_number:
    description: The security branch number (e.g., 01)
    required: true
  repository:
    description: The repository to create the security branch in (e.g., grafana/grafana-security-mirror)
    required: true
  token:
    description: GitHub token with access to the target repository
    required: true
outputs:
  branch:
    description: The name of the created security branch
    value: ${{ steps.create-security-branch.outputs.branch }}
runs:
  using: composite
  steps:
  - shell: bash
    id: create-security-branch
    env:
      GITHUB_TOKEN: ${{inputs.token}}
      INPUT_RELEASE_BRANCH: ${{inputs.release_branch}}
      INPUT_SECURITY_BRANCH_NUMBER: ${{inputs.security_branch_number}}
      INPUT_REPOSITORY: ${{inputs.repository}}
    run: |
      set -e
      # Download the action from the store
      curl --fail -L -o /tmp/create-security-branch https://github.com/grafana/grafana-github-actions-go/releases/latest/download/create-security-branch
      chmod +x /tmp/create-security-branch
      # Execute action
      /tmp/create-security-branch > branch
      echo "branch=$(cat branch)" >> "$GITHUB_OUTPUT"
