name: Auto-milestone
description: Set the milestone of a given PR based on the version of the target branch
inputs:
  token:
    description: GitHub token with access to all necessary repositories
    required: true
  pr:
    description: The PR number that should be updated
    required: true
  metrics_api_key:
    description: API key/password for a Graphite HTTP endpoint
    required: false
  metrics_api_username:
    description: Username for a Graphite HTTP endpoint
    required: false
  metrics_api_endpoint:
    description: Full URL of a Graphite HTTP endpoint
    required: false
  binary_release_tag:
    required: false
    default: "dev"
runs:
  using: composite
  steps:
  - run: |
      set -e
      # Download the action from the store
      curl --fail -L -o /tmp/auto-milestone https://github.com/grafana/grafana-github-actions-go/releases/download/${{inputs.binary_release_tag}}/auto-milestone
      chmod +x /tmp/auto-milestone
      # Execute action
      /tmp/auto-milestone ${{inputs.pr}}
    shell: bash
    env:
      GITHUB_TOKEN: ${{inputs.token}}
      INPUT_METRICS_API_USERNAME: ${{inputs.metrics_api_username}}
      INPUT_METRICS_API_KEY: ${{inputs.metrics_api_key}}
      INPUT_METRICS_API_ENDPOINT: ${{inputs.metrics_api_endpoint}}
