name: Check Branch for Open PRs
description: 'Check a branch for open PRs'
inputs:
  token:
    description: 'The GitHub token to use for authentication'
    required: true
    type: string
  branch:
    description: 'The branch to check for open PRs'
    required: true
    type: string
outputs:
  open_prs:
    description: 'JSON array of open PRs found on the branch'
    type: string

jobs:
  check-branch-for-open-prs:
  using: composite
    steps:
      - uses: actions/checkout@v4
        with:
          path: actions-go
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./actons-go/go.mod
          cache: true

      - run: cd actions-go && go run ./check-branch-for-open-prs
        shell: bash
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
          BRANCH: ${{ inputs.branch }}