name: Bump Release Branch
description: Creates a new release branch from an existing release branch
inputs:
  ownerRepo:
    description: Owner/repo which contains the branch (eg `grafana/grafana`)
    required: true
  source:
    description: The existing release branch name. (eg `release-11.3.4`)
    required: true
  binary_release_tag:
    required: false
    default: "dev"
secrets:
  token:
    description: GitHub token with access to all necessary repositories
    required: true
outputs:
  branch:
    description: The latest release branch that matches the pattern
    value: ${{ steps.bump-release.outputs.branch }}
runs:
  using: composite
  steps:
  - shell: bash
    id: bump-release
    env:
      GITHUB_TOKEN: ${{secrets.token}}
      INPUT_OWNERREPO: ${{inputs.ownerRepo}}
      INPUT_SOURCE: ${{inputs.source}}
    run: |
      set -e
      # Download the action from the store
      curl --fail -L -o /tmp/bump-release https://github.com/grafana/grafana-github-actions-go/releases/download/${{inputs.binary_release_tag}}/bump-release
      chmod +x /tmp/bump-release
      # Execute action
      echo "branch=$(/tmp/bump-release)" >> "$GITHUB_OUTPUT" 
