name: Bump Release Branch
description: Creates a new release branch from an existing release branch
inputs:
  ownerRepo:
    description: Owner/repo which contains the branch (eg `grafana/grafana`)
    required: true
  source:
    description: The existing release branch name. (eg `release-11.3.4`)
    required: true
  token:
    description: GitHub token with access to all necessary repositories
    required: true
outputs:
  branch:
    description: The latest release branch that matches the pattern
    value: ${{ steps.bump-release.outputs.branch }}
runs:
  using: composite
  steps:
    - id: build
      uses: ./build-go-binary
      with:
        binary_name: bump-release

    - id: bump-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_OWNERREPO: ${{ inputs.ownerRepo }}
        INPUT_SOURCE: ${{ inputs.source }}
        BINARY: ${{ steps.build.outputs.path }}
      run: |
        set -euo pipefail
        branch=$("${BINARY}")
        echo "branch=${branch}" >> "$GITHUB_OUTPUT"
