name: Update changelog
description: Generates a changelog for the given version and fits in into the CHANGELOG.md file
inputs:
  version:
    description: Version number invoked from workflow
    required: true
runs:
  using: composite
  steps:
  - run: |
      set -e
      # Download the action from the store
      curl -L -o /tmp/update-changelog https://github.com/grafana/grafana-github-actions-go/releases/download/test/update-changelog
      chmod +x /tmp/upload-changelog
      # Execute action
      /tmp/upload-changelog --version ${{inputs.version}} --preview
    shell: bash
    env:
      GITHUB_TOKEN: "${{github.token}}"
