name: Update changelog
description: Generates a changelog for the given version and fits in into the CHANGELOG.md file
inputs:
  version:
    description: Version number invoked from workflow
    required: true
  token:
    description: GitHub token with access to all necessary repositories
    required: true
  metrics_api_key:
    description: API key/password for a Graphite HTTP endpoint
    required: false
  metrics_api_username:
    description: Username for a Graphite HTTP endpoint
    required: false
  metrics_api_endpoint:
    description: Full URL of a Graphite HTTP endpoint
    required: false
  community_api_username:
    required: true
  community_api_key:
    required: true
  community_base_url:
    required: false
    default: "https://community.grafana.com"
  community_category_id:
    required: false
    default: "9"
  skip_pr:
    required: false
    default: "0"
  skip_community_post:
    required: false
    default: "0"
runs:
  using: composite
  steps:
    - id: build
      uses: ./build-go-binary
      with:
        binary_name: update-changelog

    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_METRICS_API_USERNAME: ${{ inputs.metrics_api_username }}
        INPUT_METRICS_API_KEY: ${{ inputs.metrics_api_key }}
        INPUT_METRICS_API_ENDPOINT: ${{ inputs.metrics_api_endpoint }}
        INPUT_COMMUNITY_API_USERNAME: ${{ inputs.community_api_username }}
        INPUT_COMMUNITY_API_KEY: ${{ inputs.community_api_key }}
        INPUT_COMMUNITY_BASE_URL: ${{ inputs.community_base_url }}
        INPUT_COMMUNITY_CATEGORY_ID: ${{ inputs.community_category_id }}
        INPUT_SKIP_PR: ${{ inputs.skip_pr }}
        INPUT_SKIP_COMMUNITY_POST: ${{ inputs.skip_community_post }}
        BINARY: ${{ steps.build.outputs.path }}
      run: |
        set -euo pipefail
        "${BINARY}"
