name: Update changelog
description: Generates a changelog for the given version and fits in into the CHANGELOG.md file
inputs:
  githubToken:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  metricsWriteAPIKey:
    description: Grafana Cloud metrics api key
    required: false
  version_call:
    description: Version number invoked from workflow
runs:
  using: composite
  steps:
  - run: go run ./main.go
    shell: bash
