name: Migrate PRs
description: Migrates PRs from one base branch to another
inputs:
  token:
    description: GitHub token
    required: true
  ownerRepo:
    description: Owner / repo to migrate PRs in. (e.g. 'grafana/grafana')
    required: true
  from:
    description: The base branch to check for open PRs
    required: true
  to:
    description: The base branch to migrate open PRs to
    required: true
runs:
  using: composite
  steps:
    - id: build
      uses: ./build-go-binary
      with:
        binary_name: migrate-open-prs

    - id: migrate-open-prs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_OWNERREPO: ${{ inputs.ownerRepo }}
        INPUT_FROM: ${{ inputs.from }}
        INPUT_TO: ${{ inputs.to }}
        BINARY: ${{ steps.build.outputs.path }}
      run: |
        set -euo pipefail
        "${BINARY}"
