name: Backport
description: Automatically creates a cherry pick PR
inputs:
  token:
    description: |
      GitHub token with read and write permissions for issues, comments, and labels.
    default: ${{ github.token }}
  labelsToAdd:
    description: Comma separated list of labels to add to the backport PR.
    required: false
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-go@v5
  - shell: bash
    env:
      GITHUB_TOKEN: ${{inputs.token}}
      INPUT_LABELS_TO_ADD: ${{inputs.labelsToAdd}}
    run: |
      go run ./backport
