name: Backport
description: Automatically creates a cherry pick PR
inputs:
  token:
    description: |
      GitHub token with read and write permissions for issues, comments, and labels.
    default: ${{ github.token }}
  labelsToAdd:
    description: Comma separated list of labels to add to the backport PR.
    required: false
runs:
  using: composite
  steps:
  - shell: bash
    env:
      GITHUB_TOKEN: ${{inputs.token}}
      INPUT_LABELS_TO_ADD: ${{inputs.labelsToAdd}}
    run: |
      set -e
      # Download the action from the store
      curl --fail -L -o /tmp/backport https://github.com/grafana/grafana-github-actions-go/releases/download/${{inputs.binary_release_tag}}/backport
      chmod +x /tmp/backport
      # Execute action
      /tmp/backport ${{inputs.pr}}
