name: Backport
description: Backports a commit to the selected release branches
inputs:
  token:
    description: GitHub token with access to all necessary repositories
    required: true
  labelsToAdd:
    description: Comma delimited list of labels to add to the backport PRs
    required: true
  binary_release_tag:
    required: false
    default: "dev"
  path:
    required: false
    default: "."
runs:
  using: composite
  steps:
  - shell: bash
    env:
      GITHUB_TOKEN: ${{inputs.token}}
      RELEASE_TAG: ${{inputs.binary_release_tag}}
      INPUT_LABELS_TO_ADD: ${{inputs.labels_to_add}}
      PR: ${{inputs.pr}}
      DIR: ${{ inputs.path }}
    run: |
      set -e
      # Download the action from the store
      curl --fail -L -o /tmp/backport https://github.com/grafana/grafana-github-actions-go/releases/download/${RELEASE_TAG}/backport
      chmod +x /tmp/backport
      cd $DIR
      # Execute action
      /tmp/backport ${PR}
