name: GitHub Release
description: Generates a new release on GitHub for the given version
inputs:
  token:
    description: GitHub token with access to all necessary repositories
    required: true
  version:
    description: The version for which to generate a release
    required: true
  metrics_api_key:
    description: API key/password for a Graphite HTTP endpoint
    required: false
  metrics_api_username:
    description: Username for a Graphite HTTP endpoint
    required: false
  metrics_api_endpoint:
    description: Full URL of a Graphite HTTP endpoint
    required: false
  latest:
    description: Mark the release as latest (1 for latest, 0 for not)
    required: false
  dry_run:
    required: false
    default: false
runs:
  using: composite
  steps:
    - id: build
      uses: ./build-go-binary
      with:
        binary_name: github-release

    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_METRICS_API_USERNAME: ${{ inputs.metrics_api_username }}
        INPUT_METRICS_API_KEY: ${{ inputs.metrics_api_key }}
        INPUT_METRICS_API_ENDPOINT: ${{ inputs.metrics_api_endpoint }}
        INPUT_LATEST: ${{ inputs.latest }}
        DRY_RUN: ${{ inputs.dry_run }}
        VERSION: ${{ inputs.version }}
        BINARY: ${{ steps.build.outputs.path }}
      run: |
        set -euo pipefail
        "${BINARY}" --preview="${DRY_RUN}" "${VERSION}"
