name: GitHub Release
description: Generates a new release on GitHub for the given version
inputs:
  token:
    description: GitHub token with access to all necessary repositories
    required: true
  version:
    description: The version for which to generate a release
    required: true
  metrics_api_key:
    description: API key/password for a Graphite HTTP endpoint
    required: false
  metrics_api_username:
    description: Username for a Graphite HTTP endpoint
    required: false
  metrics_api_endpoint:
    description: Full URL of a Graphite HTTP endpoint
    required: false
  binary_release_tag:
    required: false
    default: "dev"
  latest:
    description: Mark the release as latest (1 for latest, 0 for not)
    required: false
runs:
  using: composite
  steps:
  - run: |
      set -e
      # Download the action from the store
      curl --fail -L -o /tmp/github-release https://github.com/grafana/grafana-github-actions-go/releases/download/${{inputs.binary_release_tag}}/github-release
      chmod +x /tmp/github-release
      # Execute action
      /tmp/github-release ${{inputs.version}}
    shell: bash
    env:
      GITHUB_TOKEN: ${{inputs.token}}
      INPUT_METRICS_API_USERNAME: ${{inputs.metrics_api_username}}
      INPUT_METRICS_API_KEY: ${{inputs.metrics_api_key}}
      INPUT_METRICS_API_ENDPOINT: ${{inputs.metrics_api_endpoint}}
      INPUT_LATEST: ${{inputs.latest}}
