name: Backport
on:
  workflow_call:
    inputs:
      labelsToAdd:
        description: Comma separated list of labels to add to the backport PR.
        required: false
    secrets:
        token:
          required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - run: go run ./backport
      env:
        GITHUB_TOKEN: ${{secrets.token}}
        INPUT_LABELS_TO_ADD: ${{inputs.labelsToAdd}}
