name: Backport
on:
  workflow_call:
    inputs:
      labelsToAdd:
        description: Comma separated list of labels to add to the backport PR.
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  create-backport-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: grafana/grafana-github-actions-go
        ref: main
        path: actions-go
    - uses: actions/setup-go@v5
      with:
        go-version-file: ./actions-go/go.mod
    - run: cd actions-go && go run ./backport
      env:
        GITHUB_TOKEN: ${{secrets.token}}
        INPUT_LABELS_TO_ADD: ${{inputs.labelsToAdd}}
