name: Close milestone
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone
  workflow_call:
    inputs:
      version_call:
        description: Needs to match, exactly, the name of a milestone
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "grafana/grafana-github-actions-go"
          ref: closemilestone
      - name: Close milestone from open issues (manually invoked)
        if: ${{ github.event.inputs.version != '' }}
        uses: ./closemilestone
        with:
          version_call: ${{ github.event.inputs.version }}
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN2 }}
      - name: Close milestone from open issues (workflow invoked)
        if: ${{ inputs.version_call != '' }}
        uses: ./closemilestone
        with:
          version_call: ${{ inputs.version_call }}
          token: ${{ secrets.token2 }}

