name: Migrate open PRs
# Migrate open PRs from a superseded release branch to the current release branch
on: 
  workflow_call:
    inputs:
      prevBranch:
        description: 'The superseded release branch to check for open PRs'
        required: true
        type: string
      nextBranch:
        description: 'The current release branch to migrate open PRs'
        required: true
        type: string

jobs:
  check-and-migrate-open-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: ./check-branch-for-open-prs