name: "CI: Pull request"
on:
  pull_request: {}

jobs:
  pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{github.token}}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "1.26.3"
          cache: true
      - run: "go run ci/main.go --do-test --do-build"
