name: Update changelog
on:
  workflow_dispatch:
    inputs:
      version:
        description: Needs to match, exactly, the name of a version
        required: true
        type: string
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Something
        uses: ./update-changelog
        with:
          version: ${{ inputs.version }}
